#pragma once
#include "CreateMoveHook.h"
#include "EndScaneHook.h"
#include "ResetHook.h"
#include "LockCursorHook.h"
#include "RenderViewHook.h"
#include "PaintTreverseHook.h"
#include "ReadPixelsHook.h"
#include "ClientViewRenderHook.h"